package pl.com.mmotak.simpleweather.openweather

enum class Lang(val code: String) {
    Arabic("ar"),
    Bulgarian("ar"),
    Catalan("ar"),
    Czech("ar"),
    German("ar"),
    Greek("ar"),
    English("ar"),
    Persian("ar"),
    Finnish("fi"),
    French("fr"),
    Galician("gl"),
    Croatian("hr"),
    Hungarian("hu"),
    Italian("it"),
    Japanese("ja"),
    Korean("kr"),
    Latvian("la"),
    Lithuanian("lt"),
    Macedonian("mk"),
    Dutch("nl"),
    Polish("pl"),
    Portuguese("pt"),
    Romanian("ro"),
    Russian("ru"),
    Swedish("se"),
    Slovak("sk"),
    Slovenian("sl"),
    Spanish("es"),
    Turkish("tr"),
    Ukrainian("ua"),
    Vietnamese("vi"),
    ChineseSimplified("zh_cn"),
    ChineseTraditional("zh_tw")
}